const collection = [
  {
    title: "La vita è bella",
    year: 1997,
    genre: "Comedy-Drama",
    rating: 8.6,
    type: "movie",
  },
  {
    title: "Gomorra - La serie",
    year: 2014,
    genre: "Crime-Drama",
    rating: 8.7,
    type: "tv",
    seasons: 5,
  },
  {
    title: "Romanzo Criminale - La serie",
    year: 2008,
    genre: "Crime-Drama",
    rating: 8.6,
    type: "tv",
    seasons: 2,
  },
  {
    title: "L'isola di Pietro",
    year: 2017,
    genre: "Drama",
    rating: 7.8,
    type: "tv",
    seasons: 2,
  },
  {
    title: "Gomorra - La serie",
    year: 2014,
    genre: "Crime-Drama",
    rating: 8.7,
    type: "tv",
    seasons: 5,
  },
  {
    title: "I Cesaroni",
    year: 2006,
    genre: "Comedy",
    rating: 6.5,
    type: "tv",
    seasons: 6,
  },
  {
    title: "Il giovane Montalbano",
    year: 2012,
    genre: "Crime-Drama",
    rating: 7.8,
    type: "tv",
    seasons: 2,
  },
  {
    title: "Boris",
    year: 2007,
    genre: "Comedy",
    rating: 8.3,
    type: "tv",
    seasons: 3,
  },
  {
    title: "Suburra - La serie",
    year: 2017,
    genre: "Crime-Drama",
    rating: 7.5,
    type: "tv",
    seasons: 3,
  },
  {
    title: "L'Amica Geniale",
    year: 2018,
    genre: "Drama",
    rating: 8.6,
    type: "tv",
    seasons: 2,
  },
  {
    title: "Interstellar",
    year: 2014,
    genre: "Sci-Fi",
    rating: 8.6,
    type: "movie",
  },
  {
    title: "The Sopranos",
    year: 1999,
    genre: "Crime",
    rating: 9.2,
    type: "tv",
    seasons: 6,
  },
  {
    title: "Pulp Fiction",
    year: 1994,
    genre: "Crime",
    rating: 8.9,
    type: "movie",
  },
  {
    title: "Friends",
    year: 1994,
    genre: "Comedy",
    rating: 8.9,
    type: "tv",
    seasons: 10,
  },
  {
    title: "The Dark Knight",
    year: 2008,
    genre: "Action",
    rating: 9.0,
    type: "movie",
  },
  {
    title: "Stranger Things",
    year: 2016,
    genre: "Drama",
    rating: 8.7,
    type: "tv",
    seasons: 4,
  },
  {
    title: "The Shawshank Redemption",
    year: 1994,
    genre: "Drama",
    rating: 9.3,
    type: "movie",
  },
  {
    title: "Breaking Bad",
    year: 2008,
    genre: "Crime",
    rating: 9.5,
    type: "tv",
    seasons: 5,
  },
  {
    title: "Forrest Gump",
    year: 1994,
    genre: "Drama",
    rating: 8.8,
    type: "movie",
  },
  {
    title: "Stranger Things",
    year: 2016,
    genre: "Drama",
    rating: 8.7,
    type: "tv",
    seasons: 4,
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    genre: "Fantasy",
    rating: 8.9,
    type: "movie",
  },
  {
    title: "Stranger Things",
    year: 2016,
    genre: "Drama",
    rating: 8.7,
    type: "tv",
    seasons: 4,
  },
  {
    title: "The Wire",
    year: 2002,
    genre: "Crime",
    rating: 9.3,
    type: "tv",
    seasons: 5,
  },
  {
    title: "The Godfather: Part II",
    year: 1974,
    genre: "Crime",
    rating: 9.0,
    type: "movie",
  },
  {
    title: "Stranger Things",
    year: 2016,
    genre: "Drama",
    rating: 8.7,
    type: "tv",
    seasons: 4,
  },
];

module.exports = collection;
