const collection = [
  {
    title: "Inception",
    year: 2010,
    genre: "Sci-Fi",
    rating: 8.8,
    type: "movie",
  },
  {
    title: "Breaking Bad",
    year: 2008,
    genre: "Crime",
    rating: 9.5,
    type: "tv",
    seasons: 5,
  },
  {
    title: "The Matrix",
    year: 1999,
    genre: "Action",
    rating: 8.7,
    type: "movie",
  },
  {
    title: "Game of Thrones",
    year: 2011,
    genre: "Fantasy",
    rating: 9.3,
    type: "tv",
    seasons: 8,
  },
  {
    title: "The Godfather",
    year: 1972,
    genre: "Crime",
    rating: 9.2,
    type: "movie",
  },
  {
    title: "Stranger Things",
    year: 2016,
    genre: "Drama",
    rating: 8.7,
    type: "tv",
    seasons: 4,
  },
  {
    title: "Interstellar",
    year: 2014,
    genre: "Sci-Fi",
    rating: 8.6,
    type: "movie",
  },
  {
    title: "The Sopranos",
    year: 1999,
    genre: "Crime",
    rating: 9.2,
    type: "tv",
    seasons: 6,
  },
  {
    title: "Pulp Fiction",
    year: 1994,
    genre: "Crime",
    rating: 8.9,
    type: "movie",
  },
  {
    title: "Friends",
    year: 1994,
    genre: "Comedy",
    rating: 8.9,
    type: "tv",
    seasons: 10,
  },
  {
    title: "The Dark Knight",
    year: 2008,
    genre: "Action",
    rating: 9.0,
    type: "movie",
  },
  {
    title: "Stranger Things",
    year: 2016,
    genre: "Drama",
    rating: 8.7,
    type: "tv",
    seasons: 4,
  },
  {
    title: "The Shawshank Redemption",
    year: 1994,
    genre: "Drama",
    rating: 9.3,
    type: "movie",
  },
  {
    title: "Breaking Bad",
    year: 2008,
    genre: "Crime",
    rating: 9.5,
    type: "tv",
    seasons: 5,
  },
  {
    title: "Forrest Gump",
    year: 1994,
    genre: "Drama",
    rating: 8.8,
    type: "movie",
  },
  {
    title: "Stranger Things",
    year: 2016,
    genre: "Drama",
    rating: 8.7,
    type: "tv",
    seasons: 4,
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    genre: "Fantasy",
    rating: 8.9,
    type: "movie",
  },
  {
    title: "Stranger Things",
    year: 2016,
    genre: "Drama",
    rating: 8.7,
    type: "tv",
    seasons: 4,
  },
  {
    title: "The Wire",
    year: 2002,
    genre: "Crime",
    rating: 9.3,
    type: "tv",
    seasons: 5,
  },
  {
    title: "The Godfather: Part II",
    year: 1974,
    genre: "Crime",
    rating: 9.0,
    type: "movie",
  },
  {
    title: "Stranger Things",
    year: 2016,
    genre: "Drama",
    rating: 8.7,
    type: "tv",
    seasons: 4,
  },
];

module.exports = collection;
